name: "marine's first grid"
favicon: null
layout_spectrum: 0.88752
typography_spectrum: 0.40908749331720173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.23671595938503742
  lightness: 0.5084966642316431
  saturation: 0.592065405799076
  rhythmicContrast: 0.786086967214942
purpose: []
